//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.26 at 01:29:58 PM BRT 
//


package https.www_bcb_gov_br.pi.pacs_002._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExternalStatusReason1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExternalStatusReason1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AB03"/>
 *     &lt;enumeration value="AB09"/>
 *     &lt;enumeration value="AB11"/>
 *     &lt;enumeration value="AC03"/>
 *     &lt;enumeration value="AC06"/>
 *     &lt;enumeration value="AC07"/>
 *     &lt;enumeration value="AC14"/>
 *     &lt;enumeration value="AG03"/>
 *     &lt;enumeration value="AG12"/>
 *     &lt;enumeration value="AG13"/>
 *     &lt;enumeration value="AGNT"/>
 *     &lt;enumeration value="AM01"/>
 *     &lt;enumeration value="AM02"/>
 *     &lt;enumeration value="AM04"/>
 *     &lt;enumeration value="AM09"/>
 *     &lt;enumeration value="AM12"/>
 *     &lt;enumeration value="AM18"/>
 *     &lt;enumeration value="BE01"/>
 *     &lt;enumeration value="BE05"/>
 *     &lt;enumeration value="BE15"/>
 *     &lt;enumeration value="BE17"/>
 *     &lt;enumeration value="CH11"/>
 *     &lt;enumeration value="CH16"/>
 *     &lt;enumeration value="CN01"/>
 *     &lt;enumeration value="DS04"/>
 *     &lt;enumeration value="DS0G"/>
 *     &lt;enumeration value="DS27"/>
 *     &lt;enumeration value="DT02"/>
 *     &lt;enumeration value="DT05"/>
 *     &lt;enumeration value="DUPL"/>
 *     &lt;enumeration value="ED05"/>
 *     &lt;enumeration value="FF07"/>
 *     &lt;enumeration value="FF08"/>
 *     &lt;enumeration value="FRAD"/>
 *     &lt;enumeration value="MD01"/>
 *     &lt;enumeration value="RC09"/>
 *     &lt;enumeration value="RC10"/>
 *     &lt;enumeration value="RR04"/>
 *     &lt;enumeration value="SL02"/>
 *     &lt;enumeration value="UPAY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExternalStatusReason1Code")
@XmlEnum
public enum ExternalStatusReason1Code {

    @XmlEnumValue("AB03")
    AB_03("AB03"),
    @XmlEnumValue("AB09")
    AB_09("AB09"),
    @XmlEnumValue("AB11")
    AB_11("AB11"),
    @XmlEnumValue("AC03")
    AC_03("AC03"),
    @XmlEnumValue("AC06")
    AC_06("AC06"),
    @XmlEnumValue("AC07")
    AC_07("AC07"),
    @XmlEnumValue("AC14")
    AC_14("AC14"),
    @XmlEnumValue("AG03")
    AG_03("AG03"),
    @XmlEnumValue("AG12")
    AG_12("AG12"),
    @XmlEnumValue("AG13")
    AG_13("AG13"),
    AGNT("AGNT"),
    @XmlEnumValue("AM01")
    AM_01("AM01"),
    @XmlEnumValue("AM02")
    AM_02("AM02"),
    @XmlEnumValue("AM04")
    AM_04("AM04"),
    @XmlEnumValue("AM09")
    AM_09("AM09"),
    @XmlEnumValue("AM12")
    AM_12("AM12"),
    @XmlEnumValue("AM18")
    AM_18("AM18"),
    @XmlEnumValue("BE01")
    BE_01("BE01"),
    @XmlEnumValue("BE05")
    BE_05("BE05"),
    @XmlEnumValue("BE15")
    BE_15("BE15"),
    @XmlEnumValue("BE17")
    BE_17("BE17"),
    @XmlEnumValue("CH11")
    CH_11("CH11"),
    @XmlEnumValue("CH16")
    CH_16("CH16"),
    @XmlEnumValue("CN01")
    CN_01("CN01"),
    @XmlEnumValue("DS04")
    DS_04("DS04"),
    @XmlEnumValue("DS0G")
    DS_0_G("DS0G"),
    @XmlEnumValue("DS27")
    DS_27("DS27"),
    @XmlEnumValue("DT02")
    DT_02("DT02"),
    @XmlEnumValue("DT05")
    DT_05("DT05"),
    DUPL("DUPL"),
    @XmlEnumValue("ED05")
    ED_05("ED05"),
    @XmlEnumValue("FF07")
    FF_07("FF07"),
    @XmlEnumValue("FF08")
    FF_08("FF08"),
    FRAD("FRAD"),
    @XmlEnumValue("MD01")
    MD_01("MD01"),
    @XmlEnumValue("RC09")
    RC_09("RC09"),
    @XmlEnumValue("RC10")
    RC_10("RC10"),
    @XmlEnumValue("RR04")
    RR_04("RR04"),
    @XmlEnumValue("SL02")
    SL_02("SL02"),
    UPAY("UPAY");
    private final String value;

    ExternalStatusReason1Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExternalStatusReason1Code fromValue(String v) {
        for (ExternalStatusReason1Code c: ExternalStatusReason1Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
