external:
  dict:
    url: http://localhost:8003
  central-transfer:
    url: http://localhost:8001

notification:
  gateway:
    host: ${NOTIFICATION_GATEWAY_HOST:localhost}
    port: ${NOTIFICATION_GATEWAY_PORT:9090}
    reconnect-delay: ${NOTIFICATION_GATEWAY_RECONNECT_DELAY:1s}

spring:
  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true

bank:
  code: ${BANK_CODE}
