//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.26 at 01:29:58 PM BRT 
//


package https.www_bcb_gov_br.pi.pacs_002._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SPIEnvelopeMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SPIEnvelopeMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppHdr" type="{https://www.bcb.gov.br/pi/pacs.002/1.14}SPI.head.001.001.01"/>
 *         &lt;element name="Document" type="{https://www.bcb.gov.br/pi/pacs.002/1.14}SPI.pacs.002.001.10"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SPIEnvelopeMessage", propOrder = {
    "appHdr",
    "document"
})
public class SPIEnvelopeMessage {

    @XmlElement(name = "AppHdr", required = true)
    protected SPIHead00100101 appHdr;
    @XmlElement(name = "Document", required = true)
    protected SPIPacs00200110 document;

    /**
     * Gets the value of the appHdr property.
     * 
     * @return
     *     possible object is
     *     {@link SPIHead00100101 }
     *     
     */
    public SPIHead00100101 getAppHdr() {
        return appHdr;
    }

    /**
     * Sets the value of the appHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPIHead00100101 }
     *     
     */
    public void setAppHdr(SPIHead00100101 value) {
        this.appHdr = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * @return
     *     possible object is
     *     {@link SPIPacs00200110 }
     *     
     */
    public SPIPacs00200110 getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPIPacs00200110 }
     *     
     */
    public void setDocument(SPIPacs00200110 value) {
        this.document = value;
    }

}
