server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /api/psp-a/ {
        proxy_pass http://psp-a:8080/;
        proxy_set_header Host $http_host;
    }

    location /api/psp-b/ {
        proxy_pass http://psp-b:8080/;
        proxy_set_header Host $http_host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
