spring:
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: spi-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        max.poll.records: 100
        fetch.min.bytes: 1024
  jmx:
    enabled: false
  main:
    lazy-initialization: false
    web-application-type: reactive

spi:
  default-initial-balance: 1_000_000_000
  kafka:
    listener-concurrency: 8
  trace:
    file: /tmp/spi-trace.csv

server:
  port: 8002
