import { readFile } from 'node:fs/promises';
import test from 'node:test';
import assert from 'node:assert/strict';

const source = await readFile(new URL('./spi-test.js', import.meta.url), 'utf8');
const loadProfile = JSON.parse(await readFile(new URL('./load-profile.json', import.meta.url), 'utf8'));

test('models fixed PSP sessions with weighted in-session transaction scheduling', () => {
  assert.match(source, /const BASE_URL = 'http:\/\/localhost:8001'/);
  assert.match(source, /const GATEWAY_ADDR = 'localhost:9090'/);
  assert.match(source, /const MSG_TIMEOUT_MS = 10000/);
  assert.match(source, /const GRACEFUL_STOP = '60s'/);
  assert.match(source, /const ACTIVE_DURATION_SECONDS = 60/);
  assert.match(source, /const loadProfile = JSON\.parse\(open\('\.\/load-profile\.json'\)\)/);
  assert.match(source, /const TARGET_TX_RATE = loadProfile\.targetTxRate/);
  assert.match(source, /const HOT_PSP_COUNT = loadProfile\.hotPspCount/);
  assert.match(source, /const COLD_PSP_COUNT = loadProfile\.coldPspCount/);
  assert.match(source, /const HOT_TRAFFIC_SHARE = loadProfile\.hotTrafficShare/);
  assert.match(source, /const MAX_TX_RATE_PER_HOT_SESSION = loadProfile\.maxTxRatePerHotSession/);
  assert.match(source, /const MAX_TX_RATE_PER_COLD_SESSION = loadProfile\.maxTxRatePerColdSession/);
  assert.match(source, /const MAX_IN_FLIGHT_PER_SESSION = loadProfile\.maxInFlightPerSession/);
  assert.match(source, /const LATE_DRAIN_MS = loadProfile\.lateDrainMs/);
  assert.match(source, /const HOT_TX_RATE = TARGET_TX_RATE \* HOT_TRAFFIC_SHARE/);
  assert.match(source, /const COLD_TX_RATE = TARGET_TX_RATE \* \(1 - HOT_TRAFFIC_SHARE\)/);
  assert.match(source, /const HOT_SESSION_COUNT = Math\.max\(HOT_PSP_COUNT, Math\.ceil\(HOT_TX_RATE \/ MAX_TX_RATE_PER_HOT_SESSION\)\)/);
  assert.match(source, /const COLD_SESSION_COUNT = Math\.max\(COLD_PSP_COUNT, Math\.ceil\(COLD_TX_RATE \/ MAX_TX_RATE_PER_COLD_SESSION\)\)/);
  assert.match(source, /const HOT_TX_EVERY_MS = 1000 \/ \(HOT_TX_RATE \/ HOT_SESSION_COUNT\)/);
  assert.match(source, /const COLD_TX_EVERY_MS = 1000 \/ \(COLD_TX_RATE \/ COLD_SESSION_COUNT\)/);
  assert.match(source, /client\.load\(\['\.'\], 'notification\.proto'\)/);
  assert.match(source, /const latePacs008Notifications = new Counter\('late_pacs008_notifications'\)/);
  assert.match(source, /const latePacs002Confirmations = new Counter\('late_pacs002_confirmations'\)/);
  assert.match(source, /const lateTransactions = new Counter\('late_transactions'\)/);
  assert.match(source, /const backpressureSkips = new Counter\('backpressure_skips'\)/);
  assert.match(source, /const hotTransactionsStarted = new Counter\('hot_transactions_started'\)/);
  assert.match(source, /const coldTransactionsStarted = new Counter\('cold_transactions_started'\)/);
  assert.match(source, /const hotStartInterval = new Trend\('hot_start_interval', true\)/);
  assert.match(source, /const coldStartInterval = new Trend\('cold_start_interval', true\)/);
  assert.match(source, /const hotStartDelay = new Trend\('hot_start_delay', true\)/);
  assert.match(source, /const coldStartDelay = new Trend\('cold_start_delay', true\)/);
  assert.match(source, /const hotPacingSkips = new Counter\('hot_pacing_skips'\)/);
  assert.match(source, /const coldPacingSkips = new Counter\('cold_pacing_skips'\)/);
  assert.match(source, /hot_psps:\s*{/);
  assert.match(source, /cold_psps:\s*{/);
  assert.match(source, /executor:\s*'constant-vus'/);
  assert.match(source, /vus:\s*HOT_SESSION_COUNT/);
  assert.match(source, /vus:\s*COLD_SESSION_COUNT/);
  assert.match(source, /exec:\s*'hotPspSession'/);
  assert.match(source, /exec:\s*'coldPspSession'/);
  assert.match(source, /gracefulStop:\s*GRACEFUL_STOP/);
  assert.match(source, /summaryTrendStats:\s*\['avg', 'min', 'med', 'p\(90\)', 'p\(95\)', 'p\(99\)', 'max'\]/);
  assert.match(source, /function positiveModulo\s*\(\s*value,\s*divisor\s*\)/);
  assert.match(source, /function getHotPspNumber\s*\(\s*\)/);
  assert.match(source, /function getColdPspNumber\s*\(\s*\)/);
  assert.match(source, /function waitForMatch\s*\(\s*inbox,\s*txId,\s*timeoutMs,\s*onTimeout\s*\)/);
  assert.match(source, /onTimeout\?\.\(\)/);
  assert.match(source, /await delay\(0\)/);
  assert.match(source, /async function runPspSession\s*\(\s*pspNumber,\s*newTxEveryMs,\s*metrics\s*\)/);
  assert.match(source, /let lastStartAt = null/);
  assert.match(source, /let nextExpectedStartAt = Date\.now\(\)/);
  assert.match(source, /const waitUntilNextStartMs = nextExpectedStartAt - Date\.now\(\)/);
  assert.match(source, /if \(waitUntilNextStartMs > 0\)/);
  assert.match(source, /await delay\(waitUntilNextStartMs\)/);
  assert.match(source, /if \(startDelayMs > newTxEveryMs\)/);
  assert.match(source, /const skippedStarts = Math\.floor\(startDelayMs \/ newTxEveryMs\)/);
  assert.match(source, /metrics\.pacingSkips\.add\(skippedStarts\)/);
  assert.match(source, /nextExpectedStartAt = now \+ newTxEveryMs/);
  assert.match(source, /metrics\.transactionsStarted\.add\(1\)/);
  assert.match(source, /metrics\.startInterval\.add\(now - lastStartAt\)/);
  assert.match(source, /metrics\.startDelay\.add\(startDelayMs\)/);
  assert.match(source, /nextExpectedStartAt = scheduledStartAt \+ newTxEveryMs/);
  assert.match(source, /if \(inFlight\.size >= MAX_IN_FLIGHT_PER_SESSION\)/);
  assert.match(source, /backpressureSkips\.add\(1\)/);
  assert.match(source, /await delay\(LATE_DRAIN_MS\)/);
  assert.match(source, /lateTransactions\.add\(1\)/);
  assert.match(source, /recebedorTimedOut\[txId\] = Date\.now\(\)/);
  assert.match(source, /pagadorTimedOut\[txId\] = Date\.now\(\)/);
  assert.match(source, /export async function hotPspSession\s*\(\s*\)/);
  assert.match(source, /transactionsStarted:\s*hotTransactionsStarted/);
  assert.match(source, /startInterval:\s*hotStartInterval/);
  assert.match(source, /startDelay:\s*hotStartDelay/);
  assert.match(source, /pacingSkips:\s*hotPacingSkips/);
  assert.match(source, /export async function coldPspSession\s*\(\s*\)/);
  assert.match(source, /transactionsStarted:\s*coldTransactionsStarted/);
  assert.match(source, /startInterval:\s*coldStartInterval/);
  assert.match(source, /startDelay:\s*coldStartDelay/);
  assert.match(source, /pacingSkips:\s*coldPacingSkips/);
  assert.match(source, /export function handleSummary\s*\(\s*data\s*\)/);
  assert.match(source, /PIX LOAD SUMMARY/);
  assert.match(source, /target tx start rate/);
  assert.match(source, /active tx start rate/);
  assert.match(source, /hot tx start rate/);
  assert.match(source, /cold tx start rate/);
  assert.match(source, /hot start interval p50\/p95\/p99/);
  assert.match(source, /cold start interval p50\/p95\/p99/);
  assert.match(source, /hot start delay p50\/p95\/p99/);
  assert.match(source, /cold start delay p50\/p95\/p99/);
  assert.match(source, /hot pacing skips/);
  assert.match(source, /cold pacing skips/);
  assert.match(source, /dropped iterations/);
  assert.match(source, /backpressure skips/);
  assert.match(source, /const neverArrivedTransactionCount = transactionFailures - lateTransactionCount/);
  assert.match(source, /transactions missed SLA:/);
  assert.match(source, /transactions late:/);
  assert.match(source, /transactions never arrived:/);
  assert.match(source, /count\(data, 'dropped_iterations'\)/);
  assert.match(source, /count\(data, 'backpressure_skips'\)/);
  assert.match(source, /count\(data, 'hot_transactions_started'\)/);
  assert.match(source, /count\(data, 'cold_transactions_started'\)/);
  assert.match(source, /count\(data, 'hot_pacing_skips'\)/);
  assert.match(source, /count\(data, 'cold_pacing_skips'\)/);
  assert.match(source, /transactionsStarted \/ ACTIVE_DURATION_SECONDS/);
  assert.doesNotMatch(source, /__ENV/);
  assert.doesNotMatch(source, /parseInt/);
  assert.doesNotMatch(source, /NEW_TX_EVERY_MS/);
  assert.doesNotMatch(source, /hashString/);
  assert.doesNotMatch(source, /generateIspbFromKey/);
  assert.doesNotMatch(source, /constant-arrival-rate/);
  assert.doesNotMatch(source, /PRE_ALLOCATED_VUS/);
  assert.doesNotMatch(source, /MAX_VUS/);
});

test('keeps the default load profile easy to edit outside the k6 script', () => {
  assert.equal(loadProfile.targetTxRate, 750);
  assert.equal(loadProfile.hotPspCount, 10);
  assert.equal(loadProfile.coldPspCount, 40);
  assert.equal(loadProfile.hotTrafficShare, 0.80);
  assert.equal(loadProfile.maxTxRatePerHotSession, 12);
  assert.equal(loadProfile.maxTxRatePerColdSession, 10);
  assert.equal(loadProfile.maxInFlightPerSession, 250);
  assert.equal(loadProfile.lateDrainMs, 30000);
});
