//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.26 at 01:15:59 PM BRT 
//


package https.www_bcb_gov_br.pi.pacs_008._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_bcb_gov_br.pi.pacs_008._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Envelope_QNAME = new QName("https://www.bcb.gov.br/pi/pacs.008/1.13", "Envelope");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_bcb_gov_br.pi.pacs_008._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RfrdDocAmt }
     * 
     */
    public RfrdDocAmt createRfrdDocAmt() {
        return new RfrdDocAmt();
    }

    /**
     * Create an instance of {@link DocumentAdjustment1 }
     * 
     */
    public DocumentAdjustment1 createDocumentAdjustment1() {
        return new DocumentAdjustment1();
    }

    /**
     * Create an instance of {@link SPIEnvelopeMessage }
     * 
     */
    public SPIEnvelopeMessage createSPIEnvelopeMessage() {
        return new SPIEnvelopeMessage();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification18 }
     * 
     */
    public FinancialInstitutionIdentification18 createFinancialInstitutionIdentification18() {
        return new FinancialInstitutionIdentification18();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     * 
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link SPIPacs00800109 }
     * 
     */
    public SPIPacs00800109 createSPIPacs00800109() {
        return new SPIPacs00800109();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     * 
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link GroupHeader93 }
     * 
     */
    public GroupHeader93 createGroupHeader93() {
        return new GroupHeader93();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification8 }
     * 
     */
    public FinancialInstitutionIdentification8 createFinancialInstitutionIdentification8() {
        return new FinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link NmIdPrivateIdentification }
     * 
     */
    public NmIdPrivateIdentification createNmIdPrivateIdentification() {
        return new NmIdPrivateIdentification();
    }

    /**
     * Create an instance of {@link OrganisationIdentification29 }
     * 
     */
    public OrganisationIdentification29 createOrganisationIdentification29() {
        return new OrganisationIdentification29();
    }

    /**
     * Create an instance of {@link SignatureEnvelope }
     * 
     */
    public SignatureEnvelope createSignatureEnvelope() {
        return new SignatureEnvelope();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     * 
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation16 }
     * 
     */
    public StructuredRemittanceInformation16 createStructuredRemittanceInformation16() {
        return new StructuredRemittanceInformation16();
    }

    /**
     * Create an instance of {@link CreditTransferTransaction43 }
     * 
     */
    public CreditTransferTransaction43 createCreditTransferTransaction43() {
        return new CreditTransferTransaction43();
    }

    /**
     * Create an instance of {@link ReferredDocumentType3Choice }
     * 
     */
    public ReferredDocumentType3Choice createReferredDocumentType3Choice() {
        return new ReferredDocumentType3Choice();
    }

    /**
     * Create an instance of {@link IdOrganizationIdentification }
     * 
     */
    public IdOrganizationIdentification createIdOrganizationIdentification() {
        return new IdOrganizationIdentification();
    }

    /**
     * Create an instance of {@link PaymentIdentification13 }
     * 
     */
    public PaymentIdentification13 createPaymentIdentification13() {
        return new PaymentIdentification13();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice }
     * 
     */
    public CashAccountType2Choice createCashAccountType2Choice() {
        return new CashAccountType2Choice();
    }

    /**
     * Create an instance of {@link MandateTypeInformation2 }
     * 
     */
    public MandateTypeInformation2 createMandateTypeInformation2() {
        return new MandateTypeInformation2();
    }

    /**
     * Create an instance of {@link FIToFICustomerCreditTransferV09 }
     * 
     */
    public FIToFICustomerCreditTransferV09 createFIToFICustomerCreditTransferV09() {
        return new FIToFICustomerCreditTransferV09();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation28 }
     * 
     */
    public PaymentTypeInformation28 createPaymentTypeInformation28() {
        return new PaymentTypeInformation28();
    }

    /**
     * Create an instance of {@link ReferredDocumentType4 }
     * 
     */
    public ReferredDocumentType4 createReferredDocumentType4() {
        return new ReferredDocumentType4();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     * 
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     * 
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link Purpose2Choice }
     * 
     */
    public Purpose2Choice createPurpose2Choice() {
        return new Purpose2Choice();
    }

    /**
     * Create an instance of {@link RemittanceInformation16 }
     * 
     */
    public RemittanceInformation16 createRemittanceInformation16() {
        return new RemittanceInformation16();
    }

    /**
     * Create an instance of {@link ServiceLevel8Choice }
     * 
     */
    public ServiceLevel8Choice createServiceLevel8Choice() {
        return new ServiceLevel8Choice();
    }

    /**
     * Create an instance of {@link CreditTransferMandateData1 }
     * 
     */
    public CreditTransferMandateData1 createCreditTransferMandateData1() {
        return new CreditTransferMandateData1();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification6 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification6 createBranchAndFinancialInstitutionIdentification6() {
        return new BranchAndFinancialInstitutionIdentification6();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification5 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification5 createBranchAndFinancialInstitutionIdentification5() {
        return new BranchAndFinancialInstitutionIdentification5();
    }

    /**
     * Create an instance of {@link SettlementInstruction7 }
     * 
     */
    public SettlementInstruction7 createSettlementInstruction7() {
        return new SettlementInstruction7();
    }

    /**
     * Create an instance of {@link ProxyAccountIdentification1 }
     * 
     */
    public ProxyAccountIdentification1 createProxyAccountIdentification1() {
        return new ProxyAccountIdentification1();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice }
     * 
     */
    public LocalInstrument2Choice createLocalInstrument2Choice() {
        return new LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link SPIHead00100101 }
     * 
     */
    public SPIHead00100101 createSPIHead00100101() {
        return new SPIHead00100101();
    }

    /**
     * Create an instance of {@link PersonIdentification13 }
     * 
     */
    public PersonIdentification13 createPersonIdentification13() {
        return new PersonIdentification13();
    }

    /**
     * Create an instance of {@link OrganizationIdentification }
     * 
     */
    public OrganizationIdentification createOrganizationIdentification() {
        return new OrganizationIdentification();
    }

    /**
     * Create an instance of {@link Party9Choice }
     * 
     */
    public Party9Choice createParty9Choice() {
        return new Party9Choice();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link CashAccount38CdtrAcct }
     * 
     */
    public CashAccount38CdtrAcct createCashAccount38CdtrAcct() {
        return new CashAccount38CdtrAcct();
    }

    /**
     * Create an instance of {@link ReferredDocumentInformation7 }
     * 
     */
    public ReferredDocumentInformation7 createReferredDocumentInformation7() {
        return new ReferredDocumentInformation7();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAndAmount }
     * 
     */
    public ActiveCurrencyAndAmount createActiveCurrencyAndAmount() {
        return new ActiveCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link PrivateIdentification }
     * 
     */
    public PrivateIdentification createPrivateIdentification() {
        return new PrivateIdentification();
    }

    /**
     * Create an instance of {@link IdPrivateIdentification }
     * 
     */
    public IdPrivateIdentification createIdPrivateIdentification() {
        return new IdPrivateIdentification();
    }

    /**
     * Create an instance of {@link CashAccount38DbtrAcct }
     * 
     */
    public CashAccount38DbtrAcct createCashAccount38DbtrAcct() {
        return new CashAccount38DbtrAcct();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SPIEnvelopeMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.bcb.gov.br/pi/pacs.008/1.13", name = "Envelope")
    public JAXBElement<SPIEnvelopeMessage> createEnvelope(SPIEnvelopeMessage value) {
        return new JAXBElement<SPIEnvelopeMessage>(_Envelope_QNAME, SPIEnvelopeMessage.class, null, value);
    }

}
