//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.24 at 08:16:03 PM BRT 
//


package iso.std.iso._20022.tech.xsd.pacs_008_001;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CurrencyExchange26 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CurrencyExchange26">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UnitCcy" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.13}ActiveOrHistoricCurrencyCode" minOccurs="0"/>
 *         &lt;element name="QtdCcy" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.13}ActiveOrHistoricCurrencyCode" minOccurs="0"/>
 *         &lt;element name="PreAgrdXchgRate" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.13}BaseOneRate"/>
 *         &lt;element name="QtnDtTm" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.13}ISODateTime" minOccurs="0"/>
 *         &lt;element name="QtId" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.13}UUIDv4Identifier" minOccurs="0"/>
 *         &lt;element name="FXAgt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.13}BranchAndFinancialInstitutionIdentification8" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurrencyExchange26", propOrder = {
    "unitCcy",
    "qtdCcy",
    "preAgrdXchgRate",
    "qtnDtTm",
    "qtId",
    "fxAgt"
})
public class CurrencyExchange26 {

    @XmlElement(name = "UnitCcy")
    protected String unitCcy;
    @XmlElement(name = "QtdCcy")
    protected String qtdCcy;
    @XmlElement(name = "PreAgrdXchgRate", required = true)
    protected BigDecimal preAgrdXchgRate;
    @XmlElement(name = "QtnDtTm")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar qtnDtTm;
    @XmlElement(name = "QtId")
    protected String qtId;
    @XmlElement(name = "FXAgt")
    protected BranchAndFinancialInstitutionIdentification8 fxAgt;

    /**
     * Gets the value of the unitCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitCcy() {
        return unitCcy;
    }

    /**
     * Sets the value of the unitCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitCcy(String value) {
        this.unitCcy = value;
    }

    /**
     * Gets the value of the qtdCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtdCcy() {
        return qtdCcy;
    }

    /**
     * Sets the value of the qtdCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtdCcy(String value) {
        this.qtdCcy = value;
    }

    /**
     * Gets the value of the preAgrdXchgRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPreAgrdXchgRate() {
        return preAgrdXchgRate;
    }

    /**
     * Sets the value of the preAgrdXchgRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPreAgrdXchgRate(BigDecimal value) {
        this.preAgrdXchgRate = value;
    }

    /**
     * Gets the value of the qtnDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getQtnDtTm() {
        return qtnDtTm;
    }

    /**
     * Sets the value of the qtnDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setQtnDtTm(XMLGregorianCalendar value) {
        this.qtnDtTm = value;
    }

    /**
     * Gets the value of the qtId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtId() {
        return qtId;
    }

    /**
     * Sets the value of the qtId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtId(String value) {
        this.qtId = value;
    }

    /**
     * Gets the value of the fxAgt property.
     * 
     * @return
     *     possible object is
     *     {@link BranchAndFinancialInstitutionIdentification8 }
     *     
     */
    public BranchAndFinancialInstitutionIdentification8 getFXAgt() {
        return fxAgt;
    }

    /**
     * Sets the value of the fxAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BranchAndFinancialInstitutionIdentification8 }
     *     
     */
    public void setFXAgt(BranchAndFinancialInstitutionIdentification8 value) {
        this.fxAgt = value;
    }

}
