//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.26 at 01:15:59 PM BRT 
//


package https.www_bcb_gov_br.pi.pacs_008._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExternalCashAccountType1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExternalCashAccountType1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CACC"/>
 *     &lt;enumeration value="SLRY"/>
 *     &lt;enumeration value="SVGS"/>
 *     &lt;enumeration value="TRAN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExternalCashAccountType1Code")
@XmlEnum
public enum ExternalCashAccountType1Code {

    CACC,
    SLRY,
    SVGS,
    TRAN;

    public String value() {
        return name();
    }

    public static ExternalCashAccountType1Code fromValue(String v) {
        return valueOf(v);
    }

}
