//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.26 at 01:15:59 PM BRT 
//


package https.www_bcb_gov_br.pi.pacs_008._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrtryLclInstrmCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrtryLclInstrmCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="APDN"/>
 *     &lt;enumeration value="AUTO"/>
 *     &lt;enumeration value="DICT"/>
 *     &lt;enumeration value="INIC"/>
 *     &lt;enumeration value="MANU"/>
 *     &lt;enumeration value="QRDN"/>
 *     &lt;enumeration value="QRES"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrtryLclInstrmCode")
@XmlEnum
public enum PrtryLclInstrmCode {

    APDN,
    AUTO,
    DICT,
    INIC,
    MANU,
    QRDN,
    QRES;

    public String value() {
        return name();
    }

    public static PrtryLclInstrmCode fromValue(String v) {
        return valueOf(v);
    }

}
