//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.26 at 01:29:58 PM BRT 
//


package https.www_bcb_gov_br.pi.pacs_002._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExternalPaymentTransactionStatus1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExternalPaymentTransactionStatus1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ACCC"/>
 *     &lt;enumeration value="ACSC"/>
 *     &lt;enumeration value="ACSP"/>
 *     &lt;enumeration value="RJCT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExternalPaymentTransactionStatus1Code")
@XmlEnum
public enum ExternalPaymentTransactionStatus1Code {

    ACCC,
    ACSC,
    ACSP,
    RJCT;

    public String value() {
        return name();
    }

    public static ExternalPaymentTransactionStatus1Code fromValue(String v) {
        return valueOf(v);
    }

}
