//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.26 at 01:29:58 PM BRT 
//


package https.www_bcb_gov_br.pi.pacs_002._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_bcb_gov_br.pi.pacs_002._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Envelope_QNAME = new QName("https://www.bcb.gov.br/pi/pacs.002/1.14", "Envelope");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_bcb_gov_br.pi.pacs_002._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SPIEnvelopeMessage }
     * 
     */
    public SPIEnvelopeMessage createSPIEnvelopeMessage() {
        return new SPIEnvelopeMessage();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification5 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification5 createBranchAndFinancialInstitutionIdentification5() {
        return new BranchAndFinancialInstitutionIdentification5();
    }

    /**
     * Create an instance of {@link StatusReasonInformation12 }
     * 
     */
    public StatusReasonInformation12 createStatusReasonInformation12() {
        return new StatusReasonInformation12();
    }

    /**
     * Create an instance of {@link OriginalTransactionReference28 }
     * 
     */
    public OriginalTransactionReference28 createOriginalTransactionReference28() {
        return new OriginalTransactionReference28();
    }

    /**
     * Create an instance of {@link SPIHead00100101 }
     * 
     */
    public SPIHead00100101 createSPIHead00100101() {
        return new SPIHead00100101();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification8 }
     * 
     */
    public FinancialInstitutionIdentification8 createFinancialInstitutionIdentification8() {
        return new FinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link GroupHeader91 }
     * 
     */
    public GroupHeader91 createGroupHeader91() {
        return new GroupHeader91();
    }

    /**
     * Create an instance of {@link PaymentTransaction110 }
     * 
     */
    public PaymentTransaction110 createPaymentTransaction110() {
        return new PaymentTransaction110();
    }

    /**
     * Create an instance of {@link SignatureEnvelope }
     * 
     */
    public SignatureEnvelope createSignatureEnvelope() {
        return new SignatureEnvelope();
    }

    /**
     * Create an instance of {@link DateAndDateTime2Choice }
     * 
     */
    public DateAndDateTime2Choice createDateAndDateTime2Choice() {
        return new DateAndDateTime2Choice();
    }

    /**
     * Create an instance of {@link Party9Choice }
     * 
     */
    public Party9Choice createParty9Choice() {
        return new Party9Choice();
    }

    /**
     * Create an instance of {@link SPIPacs00200110 }
     * 
     */
    public SPIPacs00200110 createSPIPacs00200110() {
        return new SPIPacs00200110();
    }

    /**
     * Create an instance of {@link StatusReason6Choice }
     * 
     */
    public StatusReason6Choice createStatusReason6Choice() {
        return new StatusReason6Choice();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link FIToFIPaymentStatusReportV10 }
     * 
     */
    public FIToFIPaymentStatusReportV10 createFIToFIPaymentStatusReportV10() {
        return new FIToFIPaymentStatusReportV10();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SPIEnvelopeMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.bcb.gov.br/pi/pacs.002/1.14", name = "Envelope")
    public JAXBElement<SPIEnvelopeMessage> createEnvelope(SPIEnvelopeMessage value) {
        return new JAXBElement<SPIEnvelopeMessage>(_Envelope_QNAME, SPIEnvelopeMessage.class, null, value);
    }

}
