//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.26 at 01:15:59 PM BRT 
//


package https.www_bcb_gov_br.pi.pacs_008._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CreditTransferTransaction43 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditTransferTransaction43">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PmtId" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}PaymentIdentification13"/>
 *         &lt;element name="IntrBkSttlmAmt" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}ActiveCurrencyAndAmount"/>
 *         &lt;element name="AccptncDtTm" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}ISONormalisedDateTime"/>
 *         &lt;element name="ChrgBr" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}ChargeBearerType1Code"/>
 *         &lt;element name="MndtRltdInf" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}CreditTransferMandateData1"/>
 *         &lt;element name="InitgPty" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}IdOrganizationIdentification" minOccurs="0"/>
 *         &lt;element name="Dbtr" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}NmIdPrivateIdentification"/>
 *         &lt;element name="DbtrAcct" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}CashAccount38DbtrAcct"/>
 *         &lt;element name="DbtrAgt" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}BranchAndFinancialInstitutionIdentification6"/>
 *         &lt;element name="CdtrAgt" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}BranchAndFinancialInstitutionIdentification6"/>
 *         &lt;element name="Cdtr" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}IdPrivateIdentification"/>
 *         &lt;element name="CdtrAcct" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}CashAccount38CdtrAcct"/>
 *         &lt;element name="Purp" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}Purpose2Choice"/>
 *         &lt;element name="RmtInf" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}RemittanceInformation16" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditTransferTransaction43", propOrder = {
    "pmtId",
    "intrBkSttlmAmt",
    "accptncDtTm",
    "chrgBr",
    "mndtRltdInf",
    "initgPty",
    "dbtr",
    "dbtrAcct",
    "dbtrAgt",
    "cdtrAgt",
    "cdtr",
    "cdtrAcct",
    "purp",
    "rmtInf"
})
public class CreditTransferTransaction43 {

    @XmlElement(name = "PmtId", required = true)
    protected PaymentIdentification13 pmtId;
    @XmlElement(name = "IntrBkSttlmAmt", required = true)
    protected ActiveCurrencyAndAmount intrBkSttlmAmt;
    @XmlElement(name = "AccptncDtTm", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar accptncDtTm;
    @XmlElement(name = "ChrgBr", required = true)
    @XmlSchemaType(name = "string")
    protected ChargeBearerType1Code chrgBr;
    @XmlElement(name = "MndtRltdInf", required = true)
    protected CreditTransferMandateData1 mndtRltdInf;
    @XmlElement(name = "InitgPty")
    protected IdOrganizationIdentification initgPty;
    @XmlElement(name = "Dbtr", required = true)
    protected NmIdPrivateIdentification dbtr;
    @XmlElement(name = "DbtrAcct", required = true)
    protected CashAccount38DbtrAcct dbtrAcct;
    @XmlElement(name = "DbtrAgt", required = true)
    protected BranchAndFinancialInstitutionIdentification6 dbtrAgt;
    @XmlElement(name = "CdtrAgt", required = true)
    protected BranchAndFinancialInstitutionIdentification6 cdtrAgt;
    @XmlElement(name = "Cdtr", required = true)
    protected IdPrivateIdentification cdtr;
    @XmlElement(name = "CdtrAcct", required = true)
    protected CashAccount38CdtrAcct cdtrAcct;
    @XmlElement(name = "Purp", required = true)
    protected Purpose2Choice purp;
    @XmlElement(name = "RmtInf")
    protected RemittanceInformation16 rmtInf;

    /**
     * Gets the value of the pmtId property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentIdentification13 }
     *     
     */
    public PaymentIdentification13 getPmtId() {
        return pmtId;
    }

    /**
     * Sets the value of the pmtId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentIdentification13 }
     *     
     */
    public void setPmtId(PaymentIdentification13 value) {
        this.pmtId = value;
    }

    /**
     * Gets the value of the intrBkSttlmAmt property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveCurrencyAndAmount }
     *     
     */
    public ActiveCurrencyAndAmount getIntrBkSttlmAmt() {
        return intrBkSttlmAmt;
    }

    /**
     * Sets the value of the intrBkSttlmAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveCurrencyAndAmount }
     *     
     */
    public void setIntrBkSttlmAmt(ActiveCurrencyAndAmount value) {
        this.intrBkSttlmAmt = value;
    }

    /**
     * Gets the value of the accptncDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccptncDtTm() {
        return accptncDtTm;
    }

    /**
     * Sets the value of the accptncDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccptncDtTm(XMLGregorianCalendar value) {
        this.accptncDtTm = value;
    }

    /**
     * Gets the value of the chrgBr property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeBearerType1Code }
     *     
     */
    public ChargeBearerType1Code getChrgBr() {
        return chrgBr;
    }

    /**
     * Sets the value of the chrgBr property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeBearerType1Code }
     *     
     */
    public void setChrgBr(ChargeBearerType1Code value) {
        this.chrgBr = value;
    }

    /**
     * Gets the value of the mndtRltdInf property.
     * 
     * @return
     *     possible object is
     *     {@link CreditTransferMandateData1 }
     *     
     */
    public CreditTransferMandateData1 getMndtRltdInf() {
        return mndtRltdInf;
    }

    /**
     * Sets the value of the mndtRltdInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditTransferMandateData1 }
     *     
     */
    public void setMndtRltdInf(CreditTransferMandateData1 value) {
        this.mndtRltdInf = value;
    }

    /**
     * Gets the value of the initgPty property.
     * 
     * @return
     *     possible object is
     *     {@link IdOrganizationIdentification }
     *     
     */
    public IdOrganizationIdentification getInitgPty() {
        return initgPty;
    }

    /**
     * Sets the value of the initgPty property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdOrganizationIdentification }
     *     
     */
    public void setInitgPty(IdOrganizationIdentification value) {
        this.initgPty = value;
    }

    /**
     * Gets the value of the dbtr property.
     * 
     * @return
     *     possible object is
     *     {@link NmIdPrivateIdentification }
     *     
     */
    public NmIdPrivateIdentification getDbtr() {
        return dbtr;
    }

    /**
     * Sets the value of the dbtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link NmIdPrivateIdentification }
     *     
     */
    public void setDbtr(NmIdPrivateIdentification value) {
        this.dbtr = value;
    }

    /**
     * Gets the value of the dbtrAcct property.
     * 
     * @return
     *     possible object is
     *     {@link CashAccount38DbtrAcct }
     *     
     */
    public CashAccount38DbtrAcct getDbtrAcct() {
        return dbtrAcct;
    }

    /**
     * Sets the value of the dbtrAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashAccount38DbtrAcct }
     *     
     */
    public void setDbtrAcct(CashAccount38DbtrAcct value) {
        this.dbtrAcct = value;
    }

    /**
     * Gets the value of the dbtrAgt property.
     * 
     * @return
     *     possible object is
     *     {@link BranchAndFinancialInstitutionIdentification6 }
     *     
     */
    public BranchAndFinancialInstitutionIdentification6 getDbtrAgt() {
        return dbtrAgt;
    }

    /**
     * Sets the value of the dbtrAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BranchAndFinancialInstitutionIdentification6 }
     *     
     */
    public void setDbtrAgt(BranchAndFinancialInstitutionIdentification6 value) {
        this.dbtrAgt = value;
    }

    /**
     * Gets the value of the cdtrAgt property.
     * 
     * @return
     *     possible object is
     *     {@link BranchAndFinancialInstitutionIdentification6 }
     *     
     */
    public BranchAndFinancialInstitutionIdentification6 getCdtrAgt() {
        return cdtrAgt;
    }

    /**
     * Sets the value of the cdtrAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BranchAndFinancialInstitutionIdentification6 }
     *     
     */
    public void setCdtrAgt(BranchAndFinancialInstitutionIdentification6 value) {
        this.cdtrAgt = value;
    }

    /**
     * Gets the value of the cdtr property.
     * 
     * @return
     *     possible object is
     *     {@link IdPrivateIdentification }
     *     
     */
    public IdPrivateIdentification getCdtr() {
        return cdtr;
    }

    /**
     * Sets the value of the cdtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdPrivateIdentification }
     *     
     */
    public void setCdtr(IdPrivateIdentification value) {
        this.cdtr = value;
    }

    /**
     * Gets the value of the cdtrAcct property.
     * 
     * @return
     *     possible object is
     *     {@link CashAccount38CdtrAcct }
     *     
     */
    public CashAccount38CdtrAcct getCdtrAcct() {
        return cdtrAcct;
    }

    /**
     * Sets the value of the cdtrAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashAccount38CdtrAcct }
     *     
     */
    public void setCdtrAcct(CashAccount38CdtrAcct value) {
        this.cdtrAcct = value;
    }

    /**
     * Gets the value of the purp property.
     * 
     * @return
     *     possible object is
     *     {@link Purpose2Choice }
     *     
     */
    public Purpose2Choice getPurp() {
        return purp;
    }

    /**
     * Sets the value of the purp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Purpose2Choice }
     *     
     */
    public void setPurp(Purpose2Choice value) {
        this.purp = value;
    }

    /**
     * Gets the value of the rmtInf property.
     * 
     * @return
     *     possible object is
     *     {@link RemittanceInformation16 }
     *     
     */
    public RemittanceInformation16 getRmtInf() {
        return rmtInf;
    }

    /**
     * Sets the value of the rmtInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemittanceInformation16 }
     *     
     */
    public void setRmtInf(RemittanceInformation16 value) {
        this.rmtInf = value;
    }

}
