//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.26 at 01:15:59 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.bcb.gov.br/pi/pacs.008/1.13", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_bcb_gov_br.pi.pacs_008._1;
