//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.26 at 01:15:59 PM BRT 
//


package https.www_bcb_gov_br.pi.pacs_008._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StructuredRemittanceInformation16 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StructuredRemittanceInformation16">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RfrdDocInf" type="{https://www.bcb.gov.br/pi/pacs.008/1.13}ReferredDocumentInformation7"/>
 *         &lt;element ref="{https://www.bcb.gov.br/pi/pacs.008/1.13}RfrdDocAmt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StructuredRemittanceInformation16", propOrder = {
    "rfrdDocInf",
    "rfrdDocAmt"
})
public class StructuredRemittanceInformation16 {

    @XmlElement(name = "RfrdDocInf", required = true)
    protected ReferredDocumentInformation7 rfrdDocInf;
    @XmlElement(name = "RfrdDocAmt", required = true)
    protected RfrdDocAmt rfrdDocAmt;

    /**
     * Gets the value of the rfrdDocInf property.
     * 
     * @return
     *     possible object is
     *     {@link ReferredDocumentInformation7 }
     *     
     */
    public ReferredDocumentInformation7 getRfrdDocInf() {
        return rfrdDocInf;
    }

    /**
     * Sets the value of the rfrdDocInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferredDocumentInformation7 }
     *     
     */
    public void setRfrdDocInf(ReferredDocumentInformation7 value) {
        this.rfrdDocInf = value;
    }

    /**
     * Gets the value of the rfrdDocAmt property.
     * 
     * @return
     *     possible object is
     *     {@link RfrdDocAmt }
     *     
     */
    public RfrdDocAmt getRfrdDocAmt() {
        return rfrdDocAmt;
    }

    /**
     * Sets the value of the rfrdDocAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link RfrdDocAmt }
     *     
     */
    public void setRfrdDocAmt(RfrdDocAmt value) {
        this.rfrdDocAmt = value;
    }

}
